<?php
$questions = array(
	new Groupe('Les champs',
			new Question('Afficher toutes les données de tous les pays',
				'SELECT * FROM pays'),
			new Question('Afficher seulement le nom des pays',
				'SELECT nom FROM pays'),
			new Question('Afficher le ISO et le nom des pays',
				'SELECT ISO, nom FROM pays'),
			new Question('Afficher le nombre de pays (à l\'aide de COUNT)',
				'SELECT COUNT(*) AS nbPays FROM pays'),
			new Question('Afficher le nombre total d\'humains (à l\'aide de SUM)',
				'SELECT SUM(population) AS populationMondiale FROM pays'),
			new Question('En plus du nom des pays, afficher les densités de population des pays : celle déjà incluse dans la BD ET celle obtenue par calcul.',
				'SELECT nom, densite, population/superficie AS densite_calculee FROM pays'),
			new Question('Afficher la première lettre du nom ainsi que le nom des pays',
				'SELECT LEFT(nom, 1) AS initiale, nom FROM pays')
	),
	new Groupe('Les conditions',
			new Question('Afficher les pays qui commencent par la lettre A (à l\'aide de LIKE)',
				'SELECT * FROM pays WHERE nom LIKE \'A%\''),
			new Question('Afficher les pays qui se terminent par la lettre E',
				'SELECT * FROM pays WHERE nom LIKE \'%E\''),
			new Question('Afficher les pays qui commencent par la lettre A ou C (opération booléenne)',
				'SELECT * FROM pays WHERE nom LIKE \'A%\' OR nom LIKE \'C%\'','SELECT * FROM pays WHERE nom LIKE \'A%\' || nom LIKE \'C%\''),
			new Question('Afficher les pays qui commencent par la lettre A (à l\'aide de LEFT)','SELECT * FROM pays WHERE LEFT(nom,1) = \'A\''),
			new Question('Afficher les pays qui commencent par la lettre A ou C ou E (à l\'aide de IN)','SELECT * FROM pays WHERE LEFT(nom,1) IN (\'A\',\'C\',\'E\')'),
			new Question('Afficher les pays qui commencent par la lettre A jusqu\'à F','SELECT * FROM pays WHERE LEFT(nom,1) BETWEEN \'A\' AND \'F\''),
			new Question('Afficher le nombre de pays qui commencent par la lettre A (à l\'aide de LIKE)',
				'SELECT COUNT(*) FROM pays WHERE nom LIKE \'A%\''),
			new Question('Afficher les pays qui n\'ont pas d\'hiver',
				'SELECT * FROM pays WHERE moisFroids = 0'),
			new Question('Afficher les pays qui porte le même nom que sa capitale',
				'SELECT * FROM pays WHERE nom = capitale'),
			new Question('Afficher les "République" et les "Etat" qui porte le même nom que sa capitale',
				'SELECT * FROM pays WHERE (nom2 LIKE \'République%\' OR nom2 LIKE \'Etat%\') AND nom = capitale',
				'SELECT * FROM pays WHERE nom2 LIKE \'République%\' AND nom = capitale OR nom2 LIKE \'Etat$\' AND nom = capitale')
	),
	new Groupe('Le tri',
			new Question('Afficher tous les pays en ordre alphabétique',
				'SELECT * FROM pays ORDER BY nom'),
			new Question('Afficher tous les pays en ordre alphabétique inversé',
				'SELECT * FROM pays ORDER BY nom DESC'),
			new Question('Afficher tous les pays du plus populeux au moins populeux','SELECT * FROM pays ORDER BY population DESC'),
			new Question('Afficher tous les pays du plus petit au plus grand',
				'SELECT * FROM pays ORDER BY superficie'),
			new Question('Afficher tous les pays par ordre de continent puis en ordre alphabétique pour chaque continent. En excluant les pays dont le continent n\'est pas indiqué.',
				'SELECT * FROM pays WHERE continent != \'\' ORDER BY continent, nom',
				'SELECT * FROM pays WHERE continent <> \'\' ORDER BY continent, nom'),
			new Question('En plus de tous les champs des pays, afficher la longueur du nom des pays (La fonction s\'appelle LENGTH). Afficher les pays en ordre décroissant de longueur.',
				'SELECT *, LENGTH(nom) AS longueur FROM pays ORDER BY longueur DESC')
	),
	new Groupe('Les limites',
			new Question('Afficher les 10 plus grands pays.',
				'SELECT * FROM pays ORDER BY superficie DESC LIMIT 10'),
			new Question('Afficher les 5 pays les moins populeux.',
				'SELECT * FROM pays ORDER BY population LIMIT 5'),
			new Question('Par rapport au numéro précédent, afficher les 5 pays suivants. Et ensuite faire afficher les 5 pays suivants.',
				'SELECT * FROM pays ORDER BY population LIMIT 5,5','SELECT * FROM pays ORDER BY population LIMIT 10,5')
	),
	new Groupe('Cumulatif',
			new Question('Afficher, en ordre alphabétique, le nom et la capitale des pays qui commencent par la lettre A ou C ou E (à l\'aide de IN)',
				'SELECT nom, capitale FROM pays WHERE LEFT(nom,1) IN (\'A\',\'C\',\'E\') ORDER BY nom'),
			new Question('Afficher le nom, la population et la superficie des pays en ordre décroissant de population entre 8 et 9 millions d\'habitants',
				'SELECT nom, population, superficie FROM pays WHERE population BETWEEN 8000000 AND 9000000 ORDER BY population DESC')
	),
);
?>